#NUMBER_CLUSTERS=3
CREATE MODEL`hw6-big-query.supermarket_1.data001_CLUSTERS`
OPTIONS( MODEL_TYPE='KMEANS',NUM_CLUSTERS=3,KMEANS_INIT_METHOD='RANDOM') 
AS SELECT*FROM`hw6-big-query.supermarket_1.data001`

NUMBER_CLUSTERS=7
CREATE MODEL`hw6-big-query.supermarket_1.data001_CLUSTERS7`
OPTIONS( MODEL_TYPE='KMEANS',NUM_CLUSTERS=7,KMEANS_INIT_METHOD='RANDOM') 
AS SELECT*FROM`hw6-big-query.supermarket_1.data001`